[package]
name = "mercury-metrics"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mercury-core = { path = "../core" }
hdrhistogram.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
parking_lot.workspace = true
rust_decimal.workspace = true
tracing.workspace = true
