[package]
name = "mercury-strategy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mercury-core = { path = "../core" }
mercury-metrics = { path = "../metrics" }
core_affinity.workspace = true
rust_decimal.workspace = true
rust_decimal_macros.workspace = true
tokio.workspace = true
tracing.workspace = true
tract-onnx.workspace = true
